baseURL = 'https://snsalx.github.io/'
languageCode = 'en-us'
title = 'SnsAlx'

[languages.en]
disabled = false
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
weight = 1

[languages.ru]
disabled = false
languageCode = 'ru-RU'
languageDirection = 'ltr'
languageName = 'Русский'
weight = 2

[markup.highlight]
noClasses = false

